# Generated by Django 4.2.5 on 2023-09-23 08:05

import depart_api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.TextField(verbose_name='Наименование организации')),
                ('customer_address', models.CharField(max_length=64, verbose_name='Адрес организации')),
                ('customer_city', models.TextField(verbose_name='Город организации')),
            ],
            options={
                'verbose_name': 'Пользователь оборудования',
                'verbose_name_plural': 'Пользователи оборудования',
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.TextField(verbose_name='Производитель')),
                ('model', models.TextField(verbose_name='Модель')),
            ],
            options={
                'verbose_name': 'Доступное оборудование',
                'verbose_name_plural': 'Доступное оборудование',
                'db_table': 'devices',
            },
        ),
        migrations.CreateModel(
            name='DeviceInFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=64, verbose_name='Номер серии')),
                ('customer_id', models.TextField(verbose_name='Статус принаджежности')),
                ('analyzer_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='depart_api.device', verbose_name='Айди оборудования')),
                ('owner_status', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='depart_api.customer', verbose_name='Статус пользователя')),
            ],
            options={
                'verbose_name': 'Оборудование в полях',
                'verbose_name_plural': 'Оборудование в полях',
                'db_table': 'devices_in_fields',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_description', models.TextField(verbose_name='Описание завявки')),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('last_updated_dt', models.DateTimeField(blank=True, null=True, verbose_name='Время изменения статуса')),
                ('order_status', models.TextField(validators=[depart_api.models.status_validator], verbose_name='Статус заявки')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='depart_api.customer', verbose_name='Пользователь конечный')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='depart_api.deviceinfields', verbose_name='Оборудование')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'db_table': 'orders',
            },
        ),
    ]
